import React, { useEffect, useState } from 'react';
import { Plus, Mail, Save, X, Edit2, Loader2 } from 'lucide-react';
import { Apartment, ApartmentOwner, Building, Language, UserRole } from '../types';
import { supabase } from '../lib/supabase';

interface ApartmentsViewProps { apartments: Apartment[]; buildings: Building[]; currentRole: UserRole; currentLang: Language; onRefresh: () => Promise<void>; }
interface UserOption extends ApartmentOwner { id: string; }
const labels: Record<Language, any> = {
 en:{title:'Apartments',subtitle:'Apartments and their owners. Invoices belong to apartments, not users.',selectBuilding:'Select building',number:'Apartment number',building:'Building',add:'Add apartment',noApartments:'No apartments found',noOwners:'No owners assigned',recipientColumn:'Invoice recipients',recipient:'Invoice recipient',owner:'Owner',addOwner:'Add owner',addRecipient:'Add recipient',removeOwner:'Remove owner',removeRecipient:'Remove recipient',save:'Save',cancel:'Cancel',edit:'Edit apartment',saving:'Saving...',loading:'Loading...',duplicate:'An apartment with this number already exists in the selected building.',genericError:'The apartment could not be saved. Please try again.'},
 ru:{title:'Квартиры',subtitle:'Квартиры и их собственники. Квитанции относятся к квартире, а не к пользователю.',selectBuilding:'Выберите здание',number:'Номер квартиры',building:'Здание',add:'Добавить квартиру',noApartments:'Квартиры не найдены',noOwners:'Собственники не назначены',recipientColumn:'Получатели квитанции',recipient:'Получатель квитанции',owner:'Собственник',addOwner:'Добавить собственника',addRecipient:'Добавить получателя',removeOwner:'Убрать собственника',removeRecipient:'Убрать получателя',save:'Сохранить',cancel:'Отмена',edit:'Редактировать квартиру',saving:'Сохранение...',loading:'Загрузка...',duplicate:'Квартира с таким номером уже существует в выбранном здании.',genericError:'Не удалось сохранить квартиру. Попробуйте ещё раз.'},
 tr:{title:'Daireler',subtitle:'Daireler ve malikleri. Faturalar dairelere aittir.',selectBuilding:'Bina seçin',number:'Daire numarası',building:'Bina',add:'Daire ekle',noApartments:'Daire bulunamadı',noOwners:'Malik atanmadı',recipientColumn:'Fatura alıcıları',recipient:'Fatura alıcısı',owner:'Malik',addOwner:'Malik ekle',addRecipient:'Alıcı ekle',removeOwner:'Maliki kaldır',removeRecipient:'Alıcıyı kaldır',save:'Kaydet',cancel:'İptal',edit:'Daireyi düzenle',saving:'Kaydediliyor...',loading:'Yükleniyor...',duplicate:'Bu numaraya sahip bir daire zaten mevcut.',genericError:'Daire kaydedilemedi.'},
 fr:{title:'Appartements',subtitle:'Appartements et propriétaires.',selectBuilding:'Sélectionner le bâtiment',number:'Numéro d’appartement',building:'Bâtiment',add:'Ajouter',noApartments:'Aucun appartement',noOwners:'Aucun propriétaire',recipientColumn:'Destinataires de facture',recipient:'Destinataire',owner:'Propriétaire',addOwner:'Ajouter',addRecipient:'Ajouter destinataire',removeOwner:'Retirer propriétaire',removeRecipient:'Retirer destinataire',save:'Enregistrer',cancel:'Annuler',edit:'Modifier l’appartement',saving:'Enregistrement...',loading:'Chargement...',duplicate:'Cet appartement existe déjà.',genericError:'Impossible d’enregistrer.'},
 da:{title:'Lejligheder',subtitle:'Lejligheder og ejere.',selectBuilding:'Vælg bygning',number:'Lejlighedsnummer',building:'Bygning',add:'Tilføj lejlighed',noApartments:'Ingen lejligheder fundet',noOwners:'Ingen ejere',recipientColumn:'Fakturamodtagere',recipient:'Fakturamodtager',owner:'Ejer',addOwner:'Tilføj ejer',addRecipient:'Tilføj modtager',removeOwner:'Fjern ejer',removeRecipient:'Fjern modtager',save:'Gem',cancel:'Annuller',edit:'Rediger lejlighed',saving:'Gemmer...',loading:'Indlæser...',duplicate:'Lejligheden findes allerede.',genericError:'Lejligheden kunne ikke gemmes.'},
 sv:{title:'Lägenheter',subtitle:'Lägenheter och ägare.',selectBuilding:'Välj byggnad',number:'Lägenhetsnummer',building:'Byggnad',add:'Lägg till lägenhet',noApartments:'Inga lägenheter hittades',noOwners:'Inga ägare',recipientColumn:'Fakturamottagare',recipient:'Fakturamottagare',owner:'Ägare',addOwner:'Lägg till ägare',addRecipient:'Lägg till mottagare',removeOwner:'Ta bort ägare',removeRecipient:'Ta bort mottagare',save:'Spara',cancel:'Avbryt',edit:'Redigera lägenhet',saving:'Sparar...',loading:'Laddar...',duplicate:'Lägenheten finns redan.',genericError:'Lägenheten kunde inte sparas.'},
 pl:{title:'Mieszkania',subtitle:'Mieszkania i właściciele.',selectBuilding:'Wybierz budynek',number:'Numer mieszkania',building:'Budynek',add:'Dodaj mieszkanie',noApartments:'Nie znaleziono mieszkań',noOwners:'Brak właścicieli',recipientColumn:'Odbiorcy faktury',recipient:'Odbiorca',owner:'Właściciel',addOwner:'Dodaj właściciela',addRecipient:'Dodaj odbiorcę',removeOwner:'Usuń właściciela',removeRecipient:'Usuń odbiorcę',save:'Zapisz',cancel:'Anuluj',edit:'Edytuj mieszkanie',saving:'Zapisywanie...',loading:'Ładowanie...',duplicate:'Mieszkanie już istnieje.',genericError:'Nie udało się zapisać.'}
};

export const ApartmentsView: React.FC<ApartmentsViewProps> = ({ apartments, buildings, currentRole, currentLang, onRefresh }) => {
 const t=labels[currentLang];
 const [users,setUsers]=useState<UserOption[]>([]), [loadingUsers,setLoadingUsers]=useState(true), [selected,setSelected]=useState<Apartment|null>(null), [draftNumber,setDraftNumber]=useState(''), [draftBuilding,setDraftBuilding]=useState<number|''>(''), [draftOwners,setDraftOwners]=useState<string[]>([]), [draftRecipients,setDraftRecipients]=useState<string[]>([]), [newNumber,setNewNumber]=useState(''), [newBuilding,setNewBuilding]=useState<number|''>(''), [saving,setSaving]=useState(false);
 const canManage=['admin','management_company','chairman'].includes(currentRole);
 useEffect(()=>{const load=async()=>{setLoadingUsers(true);try{const {data}=await supabase.from('owners').select('id,first_name,last_name,email,default_language').order('last_name');setUsers((data||[]).map((u:any)=>({id:u.id,userId:u.id,firstName:u.first_name||'',lastName:u.last_name||'',email:u.email||'',defaultLanguage:u.default_language||'en'})))}finally{setLoadingUsers(false)}};void load()},[]);
 const openEdit=(a:Apartment)=>{setSelected(a);setDraftNumber(a.apartmentNumber);setDraftBuilding(Number(a.buildingId));setDraftOwners(a.owners.map(o=>o.userId));setDraftRecipients([...(a.invoiceRecipientIds||[])]);};
 const dirty=!!selected&&(draftNumber.trim()!==selected.apartmentNumber||Number(draftBuilding)!==Number(selected.buildingId)||draftOwners.slice().sort().join(',')!==selected.owners.map(o=>o.userId).sort().join(',')||draftRecipients.slice().sort().join(',')!==(selected.invoiceRecipientIds||[]).slice().sort().join(','));
 const saveChanges=async()=>{if(!selected||!dirty||!draftNumber.trim()||!draftBuilding)return;setSaving(true);try{
   if(draftNumber.trim()!==selected.apartmentNumber||Number(draftBuilding)!==Number(selected.buildingId)){const {error}=await supabase.from('apartments').update({building_id:Number(draftBuilding),apartment_number:draftNumber.trim()}).eq('id',selected.id);if(error)throw new Error(error.code==='23505'?t.duplicate:t.genericError)}
   const oldOwners=selected.owners.map(o=>o.userId); for(const id of oldOwners.filter(id=>!draftOwners.includes(id))){const {error}=await supabase.from('apartment_owner').delete().eq('apartment_id',selected.id).eq('user_id',id);if(error)throw error} for(const id of draftOwners.filter(id=>!oldOwners.includes(id))){const {error}=await supabase.from('apartment_owner').insert({apartment_id:selected.id,user_id:id,"ChangeUserID":id,"ChangeDate":new Date().toISOString()});if(error)throw error}
   const oldRecipients=selected.invoiceRecipientIds||[]; for(const id of oldRecipients.filter(id=>!draftRecipients.includes(id))){const {error}=await supabase.from('invoice_recipients').delete().eq('apartment_id',selected.id).eq('user_id',id);if(error)throw error} for(const id of draftRecipients.filter(id=>!oldRecipients.includes(id))){const {error}=await supabase.from('invoice_recipients').insert({apartment_id:selected.id,user_id:id});if(error)throw error}
   await onRefresh();setSelected(null);
 }catch(error){alert(error instanceof Error?error.message:t.genericError)}finally{setSaving(false)}};
 const createApartment=async(e:React.FormEvent)=>{e.preventDefault();if(!newNumber.trim()||!newBuilding)return;setSaving(true);const {error}=await supabase.from('apartments').insert({building_id:Number(newBuilding),apartment_number:newNumber.trim()});setSaving(false);if(error){alert(error.code==='23505'?t.duplicate:t.genericError);return}setNewNumber('');await onRefresh()};
 return <div className="space-y-6">
  <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-2xs"><h2 className="text-xl font-bold text-slate-900">{t.title}</h2><p className="text-xs text-slate-500 mt-1">{t.subtitle}</p>{canManage&&<form onSubmit={createApartment} className="mt-5 grid grid-cols-1 sm:grid-cols-[1fr_1fr_auto] gap-3"><select value={newBuilding} onChange={e=>setNewBuilding(e.target.value?Number(e.target.value):'')} className="px-3 py-2 border rounded-lg text-sm" required><option value="">{t.selectBuilding}</option>{buildings.map(b=><option key={b.id} value={Number(b.id)}>{b.name}</option>)}</select><input value={newNumber} onChange={e=>setNewNumber(e.target.value)} placeholder={t.number} className="px-3 py-2 border rounded-lg text-sm" required/><button disabled={saving} className="px-4 py-2 bg-teal-600 text-white rounded-lg text-sm font-bold"><Plus className="inline w-4 h-4 mr-1"/>{t.add}</button></form>}</div>
  <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 border-b"><tr><th className="px-5 py-3 text-left">{t.building}</th><th className="px-5 py-3 text-left">{t.number}</th><th className="px-5 py-3 text-left">{t.owner}</th><th className="px-5 py-3 text-left">{t.recipientColumn}</th><th className="px-5 py-3 text-right"></th></tr></thead><tbody className="divide-y">{apartments.map(a=><tr key={a.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-semibold">{a.buildingName}</td><td className="px-5 py-4 font-bold">{a.apartmentNumber}</td><td className="px-5 py-4 text-slate-600">{a.owners.length?a.owners.map(o=>`${o.firstName} ${o.lastName}`).join(', '):t.noOwners}</td><td className="px-5 py-4 text-slate-600">{(a.invoiceRecipientIds||[]).map(id=>{const u=users.find(x=>x.id===id);return u?`${u.firstName} ${u.lastName}`:''}).filter(Boolean).join(', ')||'—'}</td><td className="px-5 py-4 text-right">{canManage&&<button title={t.edit} aria-label={t.edit} onClick={()=>openEdit(a)} className="p-2 text-slate-500 hover:text-teal-700"><Edit2 className="w-4 h-4"/></button>}</td></tr>)}{!apartments.length&&<tr><td colSpan={5} className="px-5 py-10 text-center text-slate-500">{t.noApartments}</td></tr>}</tbody></table></div></div>
  {selected&&<div className="fixed inset-0 z-50 bg-slate-900/50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl p-6 max-w-lg w-full shadow-xl"><div className="flex justify-between items-center"><h3 className="font-bold text-lg">{t.edit}: {selected.apartmentNumber}</h3><button onClick={()=>!saving&&setSelected(null)}><X className="w-5 h-5"/></button></div>
   <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-5"><div><label className="block text-xs font-bold text-slate-600">{t.building}</label><select value={draftBuilding} onChange={e=>setDraftBuilding(Number(e.target.value))} className="w-full mt-1 px-3 py-2 border rounded-lg text-sm">{buildings.map(b=><option key={b.id} value={Number(b.id)}>{b.name}</option>)}</select></div><div><label className="block text-xs font-bold text-slate-600">{t.number}</label><input value={draftNumber} onChange={e=>setDraftNumber(e.target.value)} className="w-full mt-1 px-3 py-2 border rounded-lg text-sm"/></div></div>
   <div className="mt-5"><div className="text-xs font-bold text-slate-600 mb-2">{t.owner} / {t.recipientColumn}</div>{loadingUsers?<div className="py-5 text-center"><Loader2 className="w-5 h-5 mx-auto animate-spin text-slate-400"/></div>:<div className="max-h-52 overflow-auto border rounded-xl divide-y">{users.map(u=>{const owner=draftOwners.includes(u.id),recipient=draftRecipients.includes(u.id);return <div key={u.id} className="flex items-center justify-between gap-3 p-3"><div className="min-w-0"><div className="text-sm font-semibold truncate">{u.firstName} {u.lastName}</div><div className="text-[11px] text-slate-500 truncate"><Mail className="inline w-3 h-3 mr-1"/>{u.email}</div></div><div className="flex gap-2 shrink-0"><button type="button" onClick={()=>setDraftOwners(v=>owner?v.filter(x=>x!==u.id):[...v,u.id])} className={`px-2.5 py-1.5 rounded-lg text-[11px] font-bold ${owner?'bg-teal-100 text-teal-800':'bg-slate-100 text-slate-600'}`}>{owner?t.removeOwner:t.addOwner}</button>{owner&&<button type="button" onClick={()=>setDraftRecipients(v=>recipient?v.filter(x=>x!==u.id):[...v,u.id])} className={`px-2.5 py-1.5 rounded-lg text-[11px] font-bold ${recipient?'bg-indigo-100 text-indigo-800':'bg-slate-100 text-slate-600'}`}>{recipient?t.removeRecipient:t.addRecipient}</button>}</div></div>})}</div>}</div>
   <div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>!saving&&setSelected(null)} disabled={saving} className="px-4 py-2 bg-slate-100 text-slate-700 rounded-lg text-sm font-semibold">{t.cancel}</button><button type="button" disabled={!dirty||saving} onClick={()=>void saveChanges()} className={`px-4 py-2 rounded-lg text-sm font-bold ${dirty?'bg-teal-600 text-white':'bg-slate-200 text-slate-400 cursor-not-allowed'}`}>{saving?<><Loader2 className="inline w-4 h-4 mr-1 animate-spin"/>{t.saving}</>:<><Save className="inline w-4 h-4 mr-1"/>{t.save}</>}</button></div>
  </div></div>}
 </div>;
};
