import React, { useMemo, useState } from 'react';
import { Plus, Edit2, Trash2, RefreshCw, Search, X } from 'lucide-react';
import { BuildingEntity, ComplexEntity } from '../api/databaseApi';
import { UserRole, Language } from '../types';
import { formatDateTime } from '../lib/dateFormat';

interface BuildingsViewProps { buildings: BuildingEntity[]; complexes: ComplexEntity[]; selectedComplexFilter: number | 'all'; onSelectComplexFilter: (id: number | 'all') => void; onCreateBuilding: (data: { ComplexID: number; BuildingName: string }) => Promise<void>; onUpdateBuilding: (id: number, data: { ComplexID: number; BuildingName: string }) => Promise<void>; onDeleteBuilding: (id: number) => Promise<void>; onRefresh: () => void; loading: boolean; currentRole: UserRole; currentLang: Language; }
type Text={title:string;search:string;filter:string;all:string;complex:string;address:string;changed:string;add:string;name:string;save:string;cancel:string;edit:string;remove:string;noData:string;noMatch:string;required:string;selectComplex:string;saving:string;deleting:string;confirm:string;yes:string;generic:string;duplicate:string};
const texts:Record<Language,Text>={
 en:{title:'Buildings',search:'Search buildings by name...',filter:'Complex:',all:'All complexes',complex:'Complex',address:'Address',changed:'Last changed:',add:'Add Building',name:'Building Name',save:'Save',cancel:'Cancel',edit:'Edit',remove:'Delete',noData:'No buildings found',noMatch:'No buildings match your search or filter.',required:'Building name is required',selectComplex:'Complex must be selected',saving:'Saving...',deleting:'Deleting...',confirm:'Are you sure you want to delete this building?',yes:'Yes, delete',generic:'Operation failed.',duplicate:'A building with this name already exists in the selected complex.'},
 ru:{title:'Корпуса',search:'Поиск корпуса по названию...',filter:'Комплекс:',all:'Все комплексы',complex:'Комплекс',address:'Адрес',changed:'Последнее изменение:',add:'Добавить корпус',name:'Название корпуса',save:'Сохранить',cancel:'Отмена',edit:'Редактировать',remove:'Удалить',noData:'Корпуса не найдены',noMatch:'Нет корпусов, соответствующих поиску или фильтру.',required:'Название корпуса обязательно',selectComplex:'Необходимо выбрать комплекс',saving:'Сохранение...',deleting:'Удаление...',confirm:'Вы уверены, что хотите удалить этот корпус?',yes:'Да, удалить',generic:'Ошибка выполнения операции.',duplicate:'Корпус с таким названием уже существует в выбранном комплексе.'},
 tr:{title:'Binalar',search:'Bina adına göre ara...',filter:'Kompleks:',all:'Tüm kompleksler',complex:'Kompleks',address:'Adres',changed:'Son değiştirme:',add:'Bina ekle',name:'Bina adı',save:'Kaydet',cancel:'İptal',edit:'Düzenle',remove:'Sil',noData:'Bina bulunamadı',noMatch:'Arama veya filtreye uygun bina bulunamadı.',required:'Bina adı zorunludur',selectComplex:'Kompleks seçilmelidir',saving:'Kaydediliyor...',deleting:'Siliniyor...',confirm:'Bu binayı silmek istediğinizden emin misiniz?',yes:'Evet, sil',generic:'İşlem başarısız oldu.',duplicate:'Seçilen komplekste bu ada sahip bir bina zaten mevcut.'},
 fr:{title:'Bâtiments',search:'Rechercher par nom...',filter:'Résidence :',all:'Toutes les résidences',complex:'Résidence',address:'Adresse',changed:'Dernière modification :',add:'Ajouter un bâtiment',name:'Nom du bâtiment',save:'Enregistrer',cancel:'Annuler',edit:'Modifier',remove:'Supprimer',noData:'Aucun bâtiment trouvé',noMatch:'Aucun bâtiment ne correspond à la recherche ou au filtre.',required:'Le nom du bâtiment est obligatoire',selectComplex:'La résidence doit être sélectionnée',saving:'Enregistrement...',deleting:'Suppression...',confirm:'Voulez-vous supprimer ce bâtiment ?',yes:'Oui, supprimer',generic:'Échec de l’opération.',duplicate:'Un bâtiment portant ce nom existe déjà dans cette résidence.'},
 da:{title:'Bygninger',search:'Søg efter navn...',filter:'Kompleks:',all:'Alle komplekser',complex:'Kompleks',address:'Adresse',changed:'Sidst ændret:',add:'Tilføj bygning',name:'Bygningsnavn',save:'Gem',cancel:'Annuller',edit:'Rediger',remove:'Slet',noData:'Ingen bygninger fundet',noMatch:'Ingen bygninger matcher søgning eller filter.',required:'Bygningsnavn er påkrævet',selectComplex:'Kompleks skal vælges',saving:'Gemmer...',deleting:'Sletter...',confirm:'Er du sikker på, at du vil slette denne bygning?',yes:'Ja, slet',generic:'Handlingen mislykkedes.',duplicate:'En bygning med dette navn findes allerede i det valgte kompleks.'},
 sv:{title:'Byggnader',search:'Sök efter namn...',filter:'Komplex:',all:'Alla komplex',complex:'Komplex',address:'Adress',changed:'Senast ändrad:',add:'Lägg till byggnad',name:'Byggnadsnamn',save:'Spara',cancel:'Avbryt',edit:'Redigera',remove:'Ta bort',noData:'Inga byggnader hittades',noMatch:'Inga byggnader matchar sökning eller filter.',required:'Byggnadsnamn krävs',selectComplex:'Komplex måste väljas',saving:'Sparar...',deleting:'Tar bort...',confirm:'Är du säker på att du vill ta bort denna byggnad?',yes:'Ja, ta bort',generic:'Åtgärden misslyckades.',duplicate:'En byggnad med detta namn finns redan i det valda komplexet.'},
 pl:{title:'Budynki',search:'Szukaj po nazwie...',filter:'Kompleks:',all:'Wszystkie kompleksy',complex:'Kompleks',address:'Adres',changed:'Ostatnio zmieniono:',add:'Dodaj budynek',name:'Nazwa budynku',save:'Zapisz',cancel:'Anuluj',edit:'Edytuj',remove:'Usuń',noData:'Nie znaleziono budynków',noMatch:'Żaden budynek nie pasuje do wyszukiwania ani filtra.',required:'Nazwa budynku jest wymagana',selectComplex:'Należy wybrać kompleks',saving:'Zapisywanie...',deleting:'Usuwanie...',confirm:'Czy na pewno chcesz usunąć ten budynek?',yes:'Tak, usuń',generic:'Operacja nie powiodła się.',duplicate:'Budynek o tej nazwie już istnieje w wybranym kompleksie.'}
};
export const BuildingsView:React.FC<BuildingsViewProps>=({buildings,complexes,selectedComplexFilter,onSelectComplexFilter,onCreateBuilding,onUpdateBuilding,onDeleteBuilding,onRefresh,loading,currentRole,currentLang})=>{
 const t=texts[currentLang],canManage=['admin','management_company','chairman','board_member'].includes(currentRole),isAdmin=currentRole==='admin';
 const [search,setSearch]=useState(''),[editing,setEditing]=useState<BuildingEntity|null>(null),[adding,setAdding]=useState(false),[deleting,setDeleting]=useState<BuildingEntity|null>(null),[form,setForm]=useState({ComplexID:0,BuildingName:''}),[original,setOriginal]=useState({ComplexID:0,BuildingName:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const visible=useMemo(()=>buildings.filter(b=>(selectedComplexFilter==='all'||b.ComplexID===selectedComplexFilter)&&(!search||b.BuildingName.toLowerCase().includes(search.toLowerCase())||(b.ComplexName||'').toLowerCase().includes(search.toLowerCase()))),[buildings,selectedComplexFilter,search]);
 const openAdd=()=>{setForm({ComplexID:selectedComplexFilter==='all'?(complexes[0]?.ComplexID||0):selectedComplexFilter,BuildingName:''});setOriginal({ComplexID:0,BuildingName:''});setError('');setAdding(true)};
 const openEdit=(b:BuildingEntity)=>{const next={ComplexID:b.ComplexID,BuildingName:b.BuildingName};setForm(next);setOriginal(next);setEditing(b);setError('')};
 const close=()=>{setAdding(false);setEditing(null);setDeleting(null);setError('')};
 const dirty=!!editing&&(form.ComplexID!==original.ComplexID||form.BuildingName.trim()!==original.BuildingName);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!form.BuildingName.trim())return setError(t.required);if(!form.ComplexID)return setError(t.selectComplex);if(editing&&!dirty)return;setBusy(true);setError('');try{if(editing)await onUpdateBuilding(editing.BuildingID,{ComplexID:form.ComplexID,BuildingName:form.BuildingName.trim()});else await onCreateBuilding({ComplexID:form.ComplexID,BuildingName:form.BuildingName.trim()});close();await onRefresh()}catch(err:any){const message=String(err?.message||'');setError(/duplicate key|unique constraint|buildings_complex_name_unique/i.test(message)?t.duplicate:(message||t.generic))}finally{setBusy(false)}};
 const confirmDelete=async()=>{if(!deleting)return;setBusy(true);setError('');try{await onDeleteBuilding(deleting.BuildingID);close();await onRefresh()}catch(err:any){setError(err?.message||t.generic)}finally{setBusy(false)}};
 return <div className="space-y-6">
  <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-2xs flex flex-col sm:flex-row sm:items-center justify-between gap-4"><h2 className="text-xl font-bold text-slate-900">{t.title}</h2><div className="flex gap-2"><button onClick={onRefresh} disabled={loading} className="p-2 bg-slate-100 rounded-xl border border-slate-200"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button>{canManage&&<button onClick={openAdd} className="px-4 py-2 bg-teal-600 text-white text-xs font-bold rounded-xl"><Plus className="inline w-4 h-4 mr-1"/>{t.add}</button>}</div></div>
  <div className="bg-white rounded-2xl border border-slate-200 p-4 flex flex-col sm:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search} className="w-full pl-9 pr-3 py-2 border border-slate-200 rounded-lg text-sm"/></div><select value={selectedComplexFilter} onChange={e=>onSelectComplexFilter(e.target.value==='all'?'all':Number(e.target.value))} className="px-3 py-2 border border-slate-200 rounded-lg text-sm"><option value="all">{t.filter} {t.all}</option>{complexes.map(c=><option key={c.ComplexID} value={c.ComplexID}>{c.ComplexName}</option>)}</select></div>
  <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 border-b"><tr><th className="px-5 py-3 text-left">{t.name}</th><th className="px-5 py-3 text-left">{t.complex}</th><th className="px-5 py-3 text-left">{t.address}</th>{isAdmin&&<th className="px-5 py-3 text-left">{t.changed}</th>}{canManage&&<th className="px-5 py-3 text-right"></th>}</tr></thead><tbody className="divide-y">{visible.map(b=><tr key={b.BuildingID} className="hover:bg-slate-50"><td className="px-5 py-4 font-semibold">{b.BuildingName}</td><td className="px-5 py-4">{b.ComplexName||'—'}</td><td className="px-5 py-4 text-slate-500">{b.Address||'—'}</td>{isAdmin&&<td className="px-5 py-4 text-xs text-slate-500">{formatDateTime(b.ChangeDate,currentLang)}</td>}{canManage&&<td className="px-5 py-4 text-right"><button onClick={()=>openEdit(b)} title={t.edit} aria-label={t.edit} className="p-2 text-slate-500 hover:text-teal-700"><Edit2 className="w-4 h-4"/></button><button onClick={()=>setDeleting(b)} title={t.remove} aria-label={t.remove} className="p-2 text-slate-500 hover:text-red-600"><Trash2 className="w-4 h-4"/></button></td>}</tr>)}{!visible.length&&<tr><td colSpan={canManage?(isAdmin?5:4):(isAdmin?4:3)} className="px-5 py-12 text-center text-slate-500">{buildings.length?t.noMatch:t.noData}</td></tr>}</tbody></table></div></div>
  {(adding||editing)&&<div className="fixed inset-0 z-50 bg-slate-900/50 flex items-center justify-center p-4"><form onSubmit={submit} className="bg-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden"><div className="p-6 border-b border-slate-100 flex items-center justify-between"><div><h3 className="font-bold text-lg text-slate-900">{editing?t.edit:t.add}</h3><p className="text-xs text-slate-500 mt-1">{editing?'Update the building record.':'Create a new building record.'}</p></div><button type="button" onClick={close} className="p-2 text-slate-400 hover:text-slate-700"><X className="w-5 h-5"/></button></div><div className="p-6"><label className="block text-xs font-bold text-slate-600">{t.complex}</label><select value={form.ComplexID} onChange={e=>setForm({...form,ComplexID:Number(e.target.value)})} className="w-full mt-1 px-3 py-2 border rounded-xl" required>{complexes.map(c=><option key={c.ComplexID} value={c.ComplexID}>{c.ComplexName}</option>)}</select><label className="block mt-4 text-xs font-bold text-slate-600">{t.name}</label><input value={form.BuildingName} onChange={e=>setForm({...form,BuildingName:e.target.value})} className="w-full mt-1 px-3 py-2 border rounded-xl" required/>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}</div><div className="p-6 border-t border-slate-100 flex justify-end gap-2"><button type="button" onClick={close} className="px-4 py-2 rounded-xl border border-slate-300 text-slate-600">{t.cancel}</button><button disabled={busy||(!adding&&!dirty)} className="px-4 py-2 rounded-xl bg-teal-600 text-white font-semibold disabled:opacity-40">{busy?t.saving:t.save}</button></div></form></div>}
  {deleting&&<div className="fixed inset-0 z-50 bg-slate-900/50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl p-6 max-w-md w-full shadow-xl"><div className="flex justify-between items-center"><h3 className="font-bold text-lg">{t.remove}</h3><button onClick={close} className="p-2 text-slate-400"><X className="w-5 h-5"/></button></div><p className="mt-3 text-sm text-slate-600">{t.confirm}</p>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={close} className="px-4 py-2 rounded-xl border border-slate-300 text-slate-600">{t.cancel}</button><button disabled={busy} onClick={()=>void confirmDelete()} className="px-4 py-2 rounded-xl bg-red-600 text-white">{busy?t.deleting:t.yes}</button></div></div></div>}
 </div>;
};