import React, { useEffect, useState } from 'react';
import { AlertTriangle, RefreshCw, Search } from 'lucide-react';
import { Language } from '../types';
import { supabase } from '../lib/supabase';

interface ErrorRow { id: number; occurred_at: string; user_id: string | null; user_role: string | null; operation: string | null; path: string | null; error_code: string | null; technical_message: string; user_message: string; }
const labels: Record<Language, any> = {
  en: { title:'Errors', subtitle:'Application errors recorded for administrator review.', search:'Search errors...', refresh:'Refresh', loading:'Loading errors...', empty:'No errors recorded.', user:'User', date:'Date', operation:'Operation', message:'Message', technical:'Technical details' },
  ru: { title:'Ошибки', subtitle:'Ошибки приложения для просмотра администратором.', search:'Поиск ошибок...', refresh:'Обновить', loading:'Загрузка ошибок...', empty:'Ошибок пока нет.', user:'Пользователь', date:'Дата', operation:'Операция', message:'Сообщение', technical:'Технические данные' },
  tr: { title:'Hatalar', subtitle:'Yönetici incelemesi için kaydedilen uygulama hataları.', search:'Hatalarda ara...', refresh:'Yenile', loading:'Hatalar yükleniyor...', empty:'Kayıtlı hata yok.', user:'Kullanıcı', date:'Tarih', operation:'İşlem', message:'Mesaj', technical:'Teknik ayrıntılar' },
  fr: { title:'Erreurs', subtitle:'Erreurs de l’application enregistrées pour examen par l’administrateur.', search:'Rechercher des erreurs...', refresh:'Actualiser', loading:'Chargement des erreurs...', empty:'Aucune erreur enregistrée.', user:'Utilisateur', date:'Date', operation:'Opération', message:'Message', technical:'Détails techniques' },
  da: { title:'Fejl', subtitle:'Programfejl gemt til administratorens gennemgang.', search:'Søg efter fejl...', refresh:'Opdater', loading:'Indlæser fejl...', empty:'Ingen fejl registreret.', user:'Bruger', date:'Dato', operation:'Handling', message:'Meddelelse', technical:'Tekniske detaljer' },
  sv: { title:'Fel', subtitle:'Programfel som sparats för administratörens granskning.', search:'Sök efter fel...', refresh:'Uppdatera', loading:'Laddar fel...', empty:'Inga fel registrerade.', user:'Användare', date:'Datum', operation:'Åtgärd', message:'Meddelande', technical:'Tekniska detaljer' },
  pl: { title:'Błędy', subtitle:'Błędy aplikacji zapisane do wglądu administratora.', search:'Szukaj błędów...', refresh:'Odśwież', loading:'Ładowanie błędów...', empty:'Brak zapisanych błędów.', user:'Użytkownik', date:'Data', operation:'Operacja', message:'Komunikat', technical:'Szczegóły techniczne' }
};

export const ErrorLogView: React.FC<{ currentLang: Language }> = ({ currentLang }) => {
  const t = labels[currentLang]; const [rows,setRows]=useState<ErrorRow[]>([]); const [loading,setLoading]=useState(true); const [filter,setFilter]=useState('');
  const load=async()=>{setLoading(true);const {data,error}=await supabase.from('error_log').select('*').order('occurred_at',{ascending:false}).limit(500);if(error) console.error(error);setRows((data||[]) as ErrorRow[]);setLoading(false);};
  useEffect(()=>{void load();},[]);
  const filtered=rows.filter(r=>`${r.user_id||''} ${r.user_role||''} ${r.operation||''} ${r.path||''} ${r.user_message} ${r.technical_message}`.toLowerCase().includes(filter.toLowerCase()));
  return <div className="space-y-6"><div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-2xs flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold text-slate-900 flex items-center gap-2"><AlertTriangle className="w-5 h-5 text-amber-600" />{t.title}</h2><p className="text-xs text-slate-500 mt-1">{t.subtitle}</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-teal-700 text-white text-sm font-semibold disabled:opacity-50"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`} />{t.refresh}</button></div><div className="bg-white rounded-2xl border border-slate-200 shadow-2xs overflow-hidden"><div className="p-4 border-b border-slate-200"><div className="relative max-w-md"><Search className="w-3.5 h-3.5 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder={t.search} className="w-full pl-8 pr-3 py-2 bg-slate-50 border border-slate-200 rounded-lg text-xs" /></div></div>{loading?<div className="p-6 text-sm text-slate-500">{t.loading}</div>:filtered.length===0?<div className="p-6 text-sm text-slate-500">{t.empty}</div>:<div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 border-y border-slate-200"><tr><th className="px-4 py-3">{t.date}</th><th className="px-4 py-3">{t.user}</th><th className="px-4 py-3">{t.operation}</th><th className="px-4 py-3">{t.message}</th><th className="px-4 py-3">{t.technical}</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(r=><tr key={r.id} className="align-top"><td className="px-4 py-3 whitespace-nowrap">{new Date(r.occurred_at).toLocaleString()}</td><td className="px-4 py-3"><div>{r.user_role||'—'}</div><div className="text-slate-400 break-all max-w-48">{r.user_id||'—'}</div></td><td className="px-4 py-3"><div>{r.operation||'—'}</div><div className="text-slate-400">{r.path||''}</div></td><td className="px-4 py-3 font-medium">{r.user_message}</td><td className="px-4 py-3 max-w-xl"><details><summary className="cursor-pointer text-slate-500">{r.error_code||'Details'}</summary><pre className="mt-2 whitespace-pre-wrap break-words text-[11px] text-slate-600">{r.technical_message}</pre></details></td></tr>)}</tbody></table></div>}</div></div>;
};
