import React, { useEffect, useState } from 'react';
import { Mail, RefreshCw, Plus, Pencil, X } from 'lucide-react';
import { Language, UserRole } from '../types';
import { supabase } from '../lib/supabase';
import { logApplicationError } from '../lib/errorLog';

interface OwnersViewProps { currentLang: Language; currentRole: UserRole; }
type Owner = { id:string; firstName:string; lastName:string; email:string; phone:string; description:string; defaultLanguage:string; apartments:string[]; changeDate:string|null; };
type FormState = { firstName:string; lastName:string; email:string; phone:string; description:string; defaultLanguage:string };
const labels: Record<Language, any> = {
 en:{title:'Owners',subtitle:'Property owners and their apartments.',name:'Name',email:'Email',phone:'Phone',apartments:'Apartments',description:'Description',add:'Add owner',edit:'Edit',save:'Save',cancel:'Cancel',send:'Send password setup',sent:'Password setup email sent.',empty:'No owners found.',error:'The operation failed. Please try again.',required:'First name, last name and email are required.',firstName:'First name',lastName:'Last name',language:'Default language'},
 ru:{title:'Собственники',subtitle:'Собственники и принадлежащие им квартиры.',name:'ФИО',email:'Email',phone:'Телефон',apartments:'Квартиры',description:'Описание',add:'Добавить собственника',edit:'Редактировать',save:'Сохранить',cancel:'Отмена',send:'Выслать пароль',sent:'Письмо для установки пароля отправлено.',empty:'Собственники не найдены.',error:'Ошибка выполнения операции. Попробуйте ещё раз.',required:'Заполните имя, фамилию и email.',firstName:'Имя',lastName:'Фамилия',language:'Язык по умолчанию'},
 tr:{title:'Malikler',subtitle:'Malikler ve sahip oldukları daireler.',name:'Ad Soyad',email:'E-posta',phone:'Telefon',apartments:'Daireler',description:'Açıklama',add:'Malik ekle',edit:'Düzenle',save:'Kaydet',cancel:'İptal',send:'Şifre kurulumu gönder',sent:'Şifre kurulum e-postası gönderildi.',empty:'Malik bulunamadı.',error:'İşlem başarısız oldu. Lütfen tekrar deneyin.',required:'Ad, soyad ve e-posta gereklidir.',firstName:'Ad',lastName:'Soyad',language:'Varsayılan dil'},
 fr:{title:'Propriétaires',subtitle:'Propriétaires et leurs appartements.',name:'Nom',email:'E-mail',phone:'Téléphone',apartments:'Appartements',description:'Description',add:'Ajouter un propriétaire',edit:'Modifier',save:'Enregistrer',cancel:'Annuler',send:'Envoyer la configuration du mot de passe',sent:'E-mail de configuration envoyé.',empty:'Aucun propriétaire trouvé.',error:'Échec de l’opération. Veuillez réessayer.',required:'Le prénom, le nom et l’e-mail sont obligatoires.',firstName:'Prénom',lastName:'Nom',language:'Langue par défaut'},
 da:{title:'Ejere',subtitle:'Ejere og deres lejligheder.',name:'Navn',email:'E-mail',phone:'Telefon',apartments:'Lejligheder',description:'Beskrivelse',add:'Tilføj ejer',edit:'Rediger',save:'Gem',cancel:'Annuller',send:'Send adgangskodeopsætning',sent:'E-mail til adgangskodeopsætning sendt.',empty:'Ingen ejere fundet.',error:'Handlingen mislykkedes. Prøv igen.',required:'Fornavn, efternavn og e-mail er påkrævet.',firstName:'Fornavn',lastName:'Efternavn',language:'Standardsprog'},
 sv:{title:'Ägare',subtitle:'Ägare och deras lägenheter.',name:'Namn',email:'E-post',phone:'Telefon',apartments:'Lägenheter',description:'Beskrivning',add:'Lägg till ägare',edit:'Redigera',save:'Spara',cancel:'Avbryt',send:'Skicka lösenordsinställning',sent:'E-post för lösenordsinställning skickades.',empty:'Inga ägare hittades.',error:'Åtgärden misslyckades. Försök igen.',required:'Förnamn, efternamn och e-post krävs.',firstName:'Förnamn',lastName:'Efternamn',language:'Standardspråk'},
 pl:{title:'Właściciele',subtitle:'Właściciele i ich mieszkania.',name:'Imię i nazwisko',email:'E-mail',phone:'Telefon',apartments:'Mieszkania',description:'Opis',add:'Dodaj właściciela',edit:'Edytuj',save:'Zapisz',cancel:'Anuluj',send:'Wyślij konfigurację hasła',sent:'Wysłano wiadomość do ustawienia hasła.',empty:'Nie znaleziono właścicieli.',error:'Operacja nie powiodła się. Spróbuj ponownie.',required:'Imię, nazwisko i e-mail są wymagane.',firstName:'Imię',lastName:'Nazwisko',language:'Język domyślny'}
};
const emptyForm:FormState={firstName:'',lastName:'',email:'',phone:'',description:'',defaultLanguage:'en'};
export const OwnersView: React.FC<OwnersViewProps> = ({ currentLang, currentRole }) => {
 const t=labels[currentLang]; const [owners,setOwners]=useState<Owner[]>([]); const [loading,setLoading]=useState(true); const [sending,setSending]=useState<string|null>(null); const [form,setForm]=useState<FormState>(emptyForm); const [editing,setEditing]=useState<string|null>(null); const [showForm,setShowForm]=useState(false); const [saving,setSaving]=useState(false); const canManage=['admin','management_company','chairman'].includes(currentRole);
 const load=async()=>{setLoading(true);try{const [profilesResult,linksResult,apartmentsResult,buildingsResult]=await Promise.all([supabase.from('owners').select('id,first_name,last_name,email,phone,description,default_language,"ChangeDate"').order('last_name'),supabase.from('apartment_owner').select('apartment_id,user_id'),supabase.from('apartments').select('id,apartment_number,building_id'),supabase.from('buildings').select('id,name')]);if(profilesResult.error)throw profilesResult.error;if(linksResult.error)throw linksResult.error;if(apartmentsResult.error)throw apartmentsResult.error;if(buildingsResult.error)throw buildingsResult.error;const buildingMap=new Map((buildingsResult.data||[]).map((b:any)=>[Number(b.id),b.name||'']));const apartmentMap=new Map((apartmentsResult.data||[]).map((a:any)=>[Number(a.id),`${buildingMap.get(Number(a.building_id))||''} / ${a.apartment_number}`]));const links=linksResult.data||[];setOwners((profilesResult.data||[]).filter((p:any)=>links.some((l:any)=>l.user_id===p.id)).map((p:any)=>({id:p.id,firstName:p.first_name||'',lastName:p.last_name||'',email:p.email||'',phone:p.phone||'',description:p.description||'',defaultLanguage:p.default_language||'en',apartments:links.filter((l:any)=>l.user_id===p.id).map((l:any)=>apartmentMap.get(Number(l.apartment_id))).filter(Boolean) as string[],changeDate:p.ChangeDate||null})));}catch(error){await logApplicationError({operation:'owners.load',path:'/owners',error,userMessage:t.error});}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const openAdd=()=>{setEditing(null);setForm(emptyForm);setShowForm(true)};
 const openEdit=(o:Owner)=>{setEditing(o.id);setForm({firstName:o.firstName,lastName:o.lastName,email:o.email,phone:o.phone,description:o.description,defaultLanguage:o.defaultLanguage});setShowForm(true)};
 const save=async()=>{if(!form.firstName.trim()||!form.lastName.trim()||!form.email.trim()){alert(t.required);return;}setSaving(true);const operation=editing?'owners.update':'owners.create';try{if(editing){const {error}=await supabase.functions.invoke('update-owner',{body:{id:editing,first_name:form.firstName.trim(),last_name:form.lastName.trim(),email:form.email.trim(),phone:form.phone.trim(),description:form.description.trim(),default_language:form.defaultLanguage}});if(error)throw error;}else{const {error}=await supabase.functions.invoke('create-owner',{body:{first_name:form.firstName.trim(),last_name:form.lastName.trim(),email:form.email.trim(),phone:form.phone.trim(),description:form.description.trim(),default_language:form.defaultLanguage}});if(error)throw error;}setShowForm(false);setForm(emptyForm);setEditing(null);await load();}catch(error){await logApplicationError({operation,path:'/owners',error,userMessage:t.error,context:{mode:editing?'edit':'create',owner_id:editing}});alert(t.error)}finally{setSaving(false)}};
 const sendPasswordSetup=async(owner:Owner)=>{if(!owner.email)return;setSending(owner.id);try{const {error}=await supabase.auth.resetPasswordForEmail(owner.email,{redirectTo:`${window.location.origin}${window.location.pathname}`});if(error)throw error;alert(t.sent)}catch(error){await logApplicationError({operation:'owners.send_password_setup',path:'/owners',error,userMessage:t.error,context:{owner_id:owner.id}});alert(t.error)}finally{setSending(null)}};
 const field=(label:string, input:React.ReactNode)=><div className="flex flex-col gap-1"><label className="text-xs font-medium text-slate-500">{label}</label>{input}</div>;
 return <div className="space-y-6"><div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-2xs flex items-start justify-between"><div><h2 className="text-xl font-bold text-slate-900">{t.title}</h2><p className="text-xs text-slate-500 mt-1">{t.subtitle}</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="p-2 border rounded-lg text-slate-600 hover:bg-slate-50"><RefreshCw className="w-4 h-4"/></button>{canManage&&<button onClick={openAdd} className="inline-flex items-center gap-2 px-3 py-2 bg-teal-700 text-white rounded-lg text-xs font-bold"><Plus className="w-4 h-4"/>{t.add}</button>}</div></div>
 {showForm&&<div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm"><div className="flex items-center justify-between mb-4"><h3 className="font-bold">{editing?t.edit:t.add}</h3><button onClick={()=>setShowForm(false)}><X className="w-4 h-4"/></button></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{field(t.firstName,<input className="border rounded-lg px-3 py-2 text-sm" value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/>)}{field(t.lastName,<input className="border rounded-lg px-3 py-2 text-sm" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/>)}{field(t.email,<input className="border rounded-lg px-3 py-2 text-sm" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/>)}{field(t.phone,<input className="border rounded-lg px-3 py-2 text-sm" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/>)}{field(t.description,<input className="border rounded-lg px-3 py-2 text-sm" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/>)}{field(t.language,<select className="border rounded-lg px-3 py-2 text-sm" value={form.defaultLanguage} onChange={e=>setForm({...form,defaultLanguage:e.target.value})}><option value="en">English</option><option value="ru">Русский</option><option value="tr">Türkçe</option><option value="fr">Français</option><option value="da">Dansk</option><option value="sv">Svenska</option><option value="pl">Polski</option></select>)}</div><div className="flex justify-end gap-2 mt-5"><button onClick={()=>setShowForm(false)} className="px-3 py-2 border rounded-lg text-sm">{t.cancel}</button><button disabled={saving} onClick={()=>void save()} className="px-3 py-2 bg-teal-700 text-white rounded-lg text-sm font-bold">{saving?'…':t.save}</button></div></div>}
 <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 border-b"><tr><th className="px-5 py-3 text-left font-bold text-slate-600">{t.name}</th><th className="px-5 py-3 text-left font-bold text-slate-600">{t.email}</th><th className="px-5 py-3 text-left font-bold text-slate-600">{t.phone}</th><th className="px-5 py-3 text-left font-bold text-slate-600">{t.apartments}</th><th className="px-5 py-3 text-left font-bold text-slate-600">{t.description}</th>{canManage&&<th className="px-5 py-3 text-right"></th>}</tr></thead><tbody className="divide-y">{loading?<tr><td colSpan={6} className="px-5 py-10 text-center text-slate-500">…</td></tr>:owners.map(owner=><tr key={owner.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-semibold text-slate-900">{owner.firstName} {owner.lastName}</td><td className="px-5 py-4 text-slate-600">{owner.email}</td><td className="px-5 py-4 text-slate-600">{owner.phone||'—'}</td><td className="px-5 py-4 text-slate-600">{owner.apartments.join(', ')||'—'}</td><td className="px-5 py-4 text-slate-600">{owner.description||'—'}</td>{canManage&&<td className="px-5 py-4 text-right whitespace-nowrap"><button onClick={()=>openEdit(owner)} className="px-2 py-1.5 mr-1 border rounded-lg text-xs"><Pencil className="inline w-3.5 h-3.5 mr-1"/>{t.edit}</button><button disabled={sending===owner.id} onClick={()=>void sendPasswordSetup(owner)} className="px-3 py-1.5 border border-teal-200 text-teal-800 rounded-lg text-xs font-bold disabled:opacity-50"><Mail className="inline w-3.5 h-3.5 mr-1"/>{sending===owner.id?'…':t.send}</button></td>}</tr>)}{!loading&&!owners.length&&<tr><td colSpan={6} className="px-5 py-10 text-center text-slate-500">{t.empty}</td></tr>}</tbody></table></div></div></div>;
};
