import React, { useState } from 'react';
import { Wrench, Plus, Search, Building } from 'lucide-react';
import { TaskItem, UserRole, Language } from '../types';
import { translations } from '../i18n/translations';
import { TaskDetailModal } from './TaskDetailModal';

interface TasksViewProps {
  tasks: TaskItem[];
  onAddTask: (task: TaskItem) => void;
  onUpdateTask: (task: TaskItem) => void;
  currentRole: UserRole;
  currentLang: Language;
}

interface TasksUi {
  activeTasks: string; operations: string; governance: string; auditsPending: string; controllerReview: string;
  tendersCompleted: string; tenderThreshold: string; allCategories: string; allStatuses: string;
  categoryMaintenance: string; categoryRepairs: string; categoryLandscaping: string; categorySecurity: string; categoryRenovation: string;
  statusTender: string; statusAudit: string; statusBoard: string; statusApproved: string; statusProgress: string; statusCompleted: string; statusRejected: string;
  createdBy: string; inspect: string; title: string; titlePlaceholder: string; category: string; priority: string; cost: string; scope: string;
  cancel: string; save: string; low: string; medium: string; high: string; urgent: string; direct: string; tenderInfo: string; descPlaceholder: string;
}

const ui: Record<Language, TasksUi> = {
  en: { activeTasks:'Active Tasks', operations:'operations', governance:'Under Governance', auditsPending:'Financial Audits Pending', controllerReview:'Controller Review', tendersCompleted:'Tenders Completed', tenderThreshold:'> €500 Threshold', allCategories:'All Categories', allStatuses:'All Statuses', categoryMaintenance:'Maintenance', categoryRepairs:'Repairs', categoryLandscaping:'Landscaping', categorySecurity:'Security', categoryRenovation:'Renovation', statusTender:'Tender Open', statusAudit:'Financial Audit', statusBoard:'Board Review', statusApproved:'Approved', statusProgress:'In Progress', statusCompleted:'Completed', statusRejected:'Rejected', createdBy:'Created by', inspect:'Inspect Workflow →', title:'Task Title', titlePlaceholder:'e.g. Garden Irrigation Pump Replacement', category:'Category', priority:'Priority', cost:'Estimated Cost (EUR)', scope:'Scope & Description', cancel:'Cancel', save:'Create Task', low:'Low', medium:'Medium', high:'High', urgent:'Urgent', direct:'Cost < €500: Direct purchase authorization.', tenderInfo:'Cost ≥ €500: Tender procedure with competitive contractor bids will be initialized.', descPlaceholder:'Describe necessary work, location, parts required...' },
  ru: { activeTasks:'Активные задачи', operations:'операций', governance:'На контроле', auditsPending:'Ожидают финансовой проверки', controllerReview:'Проверка контролёром', tendersCompleted:'Завершённые тендеры', tenderThreshold:'Порог > €500', allCategories:'Все категории', allStatuses:'Все статусы', categoryMaintenance:'Обслуживание', categoryRepairs:'Ремонт', categoryLandscaping:'Благоустройство', categorySecurity:'Безопасность', categoryRenovation:'Реновация', statusTender:'Тендер открыт', statusAudit:'Финансовая проверка', statusBoard:'На рассмотрении правления', statusApproved:'Одобрено', statusProgress:'В работе', statusCompleted:'Завершено', statusRejected:'Отклонено', createdBy:'Создано', inspect:'Открыть процесс →', title:'Название задачи', titlePlaceholder:'например: Замена насоса полива сада', category:'Категория', priority:'Приоритет', cost:'Ориентировочная стоимость (EUR)', scope:'Объём и описание', cancel:'Отмена', save:'Создать задачу', low:'Низкий', medium:'Средний', high:'Высокий', urgent:'Срочный', direct:'Стоимость < €500: прямая закупка.', tenderInfo:'Стоимость ≥ €500: будет запущена тендерная процедура с предложениями подрядчиков.', descPlaceholder:'Опишите работы, место и необходимые материалы...' },
  tr: { activeTasks:'Aktif Görevler', operations:'işlem', governance:'Kontrol altında', auditsPending:'Bekleyen Mali Kontroller', controllerReview:'Kontrolör incelemesi', tendersCompleted:'Tamamlanan İhaleler', tenderThreshold:'€500 üzeri eşik', allCategories:'Tüm kategoriler', allStatuses:'Tüm durumlar', categoryMaintenance:'Bakım', categoryRepairs:'Onarım', categoryLandscaping:'Peyzaj', categorySecurity:'Güvenlik', categoryRenovation:'Yenileme', statusTender:'İhale açık', statusAudit:'Mali inceleme', statusBoard:'Yönetim kurulu incelemesi', statusApproved:'Onaylandı', statusProgress:'Devam ediyor', statusCompleted:'Tamamlandı', statusRejected:'Reddedildi', createdBy:'Oluşturan', inspect:'Süreci incele →', title:'Görev başlığı', titlePlaceholder:'ör. Bahçe sulama pompası değişimi', category:'Kategori', priority:'Öncelik', cost:'Tahmini maliyet (EUR)', scope:'Kapsam ve açıklama', cancel:'İptal', save:'Görev oluştur', low:'Düşük', medium:'Orta', high:'Yüksek', urgent:'Acil', direct:'Maliyet < €500: doğrudan satın alma.', tenderInfo:'Maliyet ≥ €500: rekabetçi teklifler için ihale süreci başlatılır.', descPlaceholder:'Gerekli işi, konumu ve parçaları açıklayın...' },
  fr: { activeTasks:'Tâches actives', operations:'opérations', governance:'Sous contrôle', auditsPending:'Audits financiers en attente', controllerReview:'Contrôle financier', tendersCompleted:'Appels d’offres terminés', tenderThreshold:'Seuil > 500 €', allCategories:'Toutes les catégories', allStatuses:'Tous les statuts', categoryMaintenance:'Maintenance', categoryRepairs:'Réparations', categoryLandscaping:'Aménagement paysager', categorySecurity:'Sécurité', categoryRenovation:'Rénovation', statusTender:'Appel d’offres ouvert', statusAudit:'Audit financier', statusBoard:'Examen du Conseil', statusApproved:'Approuvé', statusProgress:'En cours', statusCompleted:'Terminé', statusRejected:'Rejeté', createdBy:'Créé par', inspect:'Voir le processus →', title:'Titre de la tâche', titlePlaceholder:'ex. Remplacement de la pompe d’irrigation', category:'Catégorie', priority:'Priorité', cost:'Coût estimé (EUR)', scope:'Périmètre et description', cancel:'Annuler', save:'Créer la tâche', low:'Faible', medium:'Moyenne', high:'Élevée', urgent:'Urgente', direct:'Coût < 500 € : achat direct.', tenderInfo:'Coût ≥ 500 € : procédure d’appel d’offres avec plusieurs devis.', descPlaceholder:'Décrivez les travaux, le lieu et les pièces nécessaires...' },
  da: { activeTasks:'Aktive opgaver', operations:'operationer', governance:'Under styring', auditsPending:'Finansielle kontroller i kø', controllerReview:'Kontrolgennemgang', tendersCompleted:'Afsluttede udbud', tenderThreshold:'Tærskel > €500', allCategories:'Alle kategorier', allStatuses:'Alle statusser', categoryMaintenance:'Vedligeholdelse', categoryRepairs:'Reparationer', categoryLandscaping:'Landskab', categorySecurity:'Sikkerhed', categoryRenovation:'Renovering', statusTender:'Udbud åbent', statusAudit:'Finansiel kontrol', statusBoard:'Bestyrelsesbehandling', statusApproved:'Godkendt', statusProgress:'I gang', statusCompleted:'Afsluttet', statusRejected:'Afvist', createdBy:'Oprettet af', inspect:'Se arbejdsgang →', title:'Opgavetitel', titlePlaceholder:'fx Udskiftning af havevandingspumpe', category:'Kategori', priority:'Prioritet', cost:'Estimeret pris (EUR)', scope:'Omfang og beskrivelse', cancel:'Annuller', save:'Opret opgave', low:'Lav', medium:'Mellem', high:'Høj', urgent:'Haster', direct:'Pris < €500: direkte indkøb.', tenderInfo:'Pris ≥ €500: udbudsprocedure med konkurrerende tilbud startes.', descPlaceholder:'Beskriv arbejdet, placeringen og nødvendige dele...' },
  sv: { activeTasks:'Aktiva ärenden', operations:'åtgärder', governance:'Under styrning', auditsPending:'Väntande ekonomiska kontroller', controllerReview:'Kontrollgranskning', tendersCompleted:'Slutförda upphandlingar', tenderThreshold:'Tröskel > €500', allCategories:'Alla kategorier', allStatuses:'Alla statusar', categoryMaintenance:'Underhåll', categoryRepairs:'Reparationer', categoryLandscaping:'Markarbete', categorySecurity:'Säkerhet', categoryRenovation:'Renovering', statusTender:'Upphandling öppen', statusAudit:'Ekonomisk granskning', statusBoard:'Styrelsegranskning', statusApproved:'Godkänd', statusProgress:'Pågår', statusCompleted:'Slutförd', statusRejected:'Avvisad', createdBy:'Skapad av', inspect:'Visa arbetsflöde →', title:'Ärendets titel', titlePlaceholder:'t.ex. byte av bevattningspump', category:'Kategori', priority:'Prioritet', cost:'Beräknad kostnad (EUR)', scope:'Omfattning och beskrivning', cancel:'Avbryt', save:'Skapa ärende', low:'Låg', medium:'Medel', high:'Hög', urgent:'Brådskande', direct:'Kostnad < €500: direktinköp.', tenderInfo:'Kostnad ≥ €500: upphandlingsprocess med konkurrerande offerter startas.', descPlaceholder:'Beskriv arbete, plats och nödvändiga delar...' },
  pl: { activeTasks:'Aktywne zadania', operations:'operacji', governance:'Pod nadzorem', auditsPending:'Oczekujące kontrole finansowe', controllerReview:'Kontrola finansowa', tendersCompleted:'Zakończone przetargi', tenderThreshold:'Próg > 500 €', allCategories:'Wszystkie kategorie', allStatuses:'Wszystkie statusy', categoryMaintenance:'Konserwacja', categoryRepairs:'Naprawy', categoryLandscaping:'Tereny zielone', categorySecurity:'Bezpieczeństwo', categoryRenovation:'Remont', statusTender:'Przetarg otwarty', statusAudit:'Kontrola finansowa', statusBoard:'Rozpatrywanie przez Zarząd', statusApproved:'Zatwierdzone', statusProgress:'W toku', statusCompleted:'Zakończone', statusRejected:'Odrzucone', createdBy:'Utworzone przez', inspect:'Otwórz przebieg →', title:'Tytuł zadania', titlePlaceholder:'np. Wymiana pompy nawadniającej', category:'Kategoria', priority:'Priorytet', cost:'Szacowany koszt (EUR)', scope:'Zakres i opis', cancel:'Anuluj', save:'Utwórz zadanie', low:'Niski', medium:'Średni', high:'Wysoki', urgent:'Pilne', direct:'Koszt < 500 €: zakup bezpośredni.', tenderInfo:'Koszt ≥ 500 €: zostanie uruchomiony przetarg z konkurencyjnymi ofertami.', descPlaceholder:'Opisz zakres prac, miejsce i potrzebne części...' }
};

export const TasksView: React.FC<TasksViewProps> = ({ tasks, onAddTask, onUpdateTask, currentRole, currentLang }) => {
  const t = translations[currentLang];
  const l = ui[currentLang];
  const canCreate = ['admin', 'management_company', 'chairman', 'board_member', 'site_staff'].includes(currentRole);
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [selectedStatus, setSelectedStatus] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [isCreatingTask, setIsCreatingTask] = useState(false);
  const [activeTaskModal, setActiveTaskModal] = useState<TaskItem | null>(null);
  const [newTaskTitle, setNewTaskTitle] = useState('');
  const [newTaskDesc, setNewTaskDesc] = useState('');
  const [newTaskCost, setNewTaskCost] = useState<number>(650);
  const [newTaskCategory, setNewTaskCategory] = useState<TaskItem['category']>('maintenance');
  const [newTaskPriority, setNewTaskPriority] = useState<TaskItem['priority']>('medium');

  const categoryLabel = (value: string) => ({ maintenance:l.categoryMaintenance, repairs:l.categoryRepairs, landscaping:l.categoryLandscaping, security:l.categorySecurity, renovation:l.categoryRenovation }[value] || value);
  const priorityLabel = (value: string) => ({ low:l.low, medium:l.medium, high:l.high, urgent:l.urgent }[value] || value);
  const auditLabel = (value: string) => value === 'verified_correct' ? t.auditCorrect : value === 'discrepancy_flagged' ? t.auditDiscrepancy : t.auditPending;
  const filteredTasks = tasks.filter(task => `${task.title} ${task.description} ${task.creatorName}`.toLowerCase().includes(searchQuery.toLowerCase()) && (selectedCategory === 'all' || task.category === selectedCategory) && (selectedStatus === 'all' || task.status === selectedStatus));

  const handleCreateSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTaskTitle.trim()) return;
    const requiresTender = Number(newTaskCost) >= 500;
    const now = Date.now();
    const created: TaskItem = {
      id:`task-${now}`, title:newTaskTitle.trim(), description:newTaskDesc.trim(), category:newTaskCategory, priority:newTaskPriority,
      status:requiresTender?'tender_open':'board_review', createdByRole:currentRole, creatorName:currentRole.replace('_',' ').toUpperCase(), estimatedCost:Number(newTaskCost), currency:'EUR', requiresTender,
      tenderProposals:requiresTender?[{id:`prop-${now}-1`,contractorName:'Akdeniz Yapı & Teknik Ltd.',companyRegNo:'TR-AL-3921',price:Number(newTaskCost)-30,currency:'EUR',scopeSummary:'Full turnkey execution according to specification.',validityPeriod:'30 Days',commercialOfferDocName:'Offer_AkdenizYapi.pdf',isSelected:true,submittedAt:new Date().toISOString().split('T')[0]},{id:`prop-${now}-2`,contractorName:'Toros Mühendislik A.Ş.',companyRegNo:'TR-AL-8812',price:Number(newTaskCost)+50,currency:'EUR',scopeSummary:'Standard quote with certified components.',validityPeriod:'15 Days',commercialOfferDocName:'Toros_Quote.pdf',isSelected:false,submittedAt:new Date().toISOString().split('T')[0]}]:[],
      financialAudit:{status:'pending',checklist:{tenderCompleted:requiresTender,proposalsVerified:false,priceReasonable:true,taxInvoiceAttached:false,boardApproved:false,proofOfExecutionAttached:false}}, boardApprovals:[], comments:[], createdAt:new Date().toISOString().split('T')[0], deadline:'2026-03-31'
    };
    onAddTask(created); setIsCreatingTask(false); setNewTaskTitle(''); setNewTaskDesc('');
  };

  return <div className="space-y-6">
    <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-2xs flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h2 className="text-xl font-bold text-slate-900">{t.tasksTitle}</h2><p className="text-xs text-slate-500 mt-1">{t.tasksSubtitle}</p></div>{canCreate&&<button id="create-task-btn" onClick={()=>setIsCreatingTask(true)} className="inline-flex items-center px-4 py-2 bg-teal-600 hover:bg-teal-500 text-white text-xs font-bold rounded-xl"><Plus className="w-4 h-4 mr-1.5"/>{t.createTask}</button>}</div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div className="p-4 bg-white rounded-2xl border border-slate-200 shadow-2xs"><span className="text-xs font-semibold text-slate-500 block">{l.activeTasks}</span><p className="text-2xl font-black text-slate-900 mt-1">{tasks.length} {l.operations}</p><span className="text-[11px] text-teal-700 font-semibold">{l.governance}</span></div><div className="p-4 bg-amber-50/80 rounded-2xl border border-amber-200 shadow-2xs"><span className="text-xs font-semibold text-amber-800 block">{l.auditsPending}</span><p className="text-2xl font-black text-amber-950 mt-1">{tasks.filter(tk=>tk.financialAudit.status==='pending').length}</p><span className="text-[11px] text-amber-700 font-semibold">{l.controllerReview}</span></div><div className="p-4 bg-teal-50/80 rounded-2xl border border-teal-200 shadow-2xs"><span className="text-xs font-semibold text-teal-800 block">{l.tendersCompleted}</span><p className="text-2xl font-black text-teal-950 mt-1">{tasks.filter(tk=>tk.requiresTender).length}</p><span className="text-[11px] text-teal-700 font-semibold">{l.tenderThreshold}</span></div></div>
    <div className="flex flex-col sm:flex-row items-center gap-3 bg-white p-4 rounded-2xl border border-slate-200 shadow-2xs"><div className="relative flex-1 w-full"><Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input type="text" placeholder={t.search} value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} className="w-full pl-9 pr-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs focus:ring-2 focus:ring-teal-500 focus:outline-none"/></div><div className="flex items-center gap-2 w-full sm:w-auto"><select value={selectedCategory} onChange={e=>setSelectedCategory(e.target.value)} className="px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-semibold text-slate-700"><option value="all">{l.allCategories}</option><option value="maintenance">{l.categoryMaintenance}</option><option value="repairs">{l.categoryRepairs}</option><option value="landscaping">{l.categoryLandscaping}</option><option value="security">{l.categorySecurity}</option><option value="renovation">{l.categoryRenovation}</option></select><select value={selectedStatus} onChange={e=>setSelectedStatus(e.target.value)} className="px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-semibold text-slate-700"><option value="all">{l.allStatuses}</option><option value="tender_open">{l.statusTender}</option><option value="financial_audit">{l.statusAudit}</option><option value="board_review">{l.statusBoard}</option><option value="approved">{l.statusApproved}</option><option value="in_progress">{l.statusProgress}</option><option value="completed">{l.statusCompleted}</option></select></div></div>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">{filteredTasks.map(task=><div key={task.id} onClick={()=>setActiveTaskModal(task)} className="bg-white rounded-2xl p-5 border border-slate-200 shadow-2xs hover:shadow-md transition-all cursor-pointer flex flex-col justify-between space-y-4"><div className="space-y-3"><div className="flex items-center justify-between"><div className="flex items-center space-x-2"><span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold ${task.priority==='urgent'?'bg-red-100 text-red-800':task.priority==='high'?'bg-orange-100 text-orange-800':'bg-slate-100 text-slate-700'}`}>{priorityLabel(task.priority)}</span><span className="px-2 py-0.5 rounded-md text-[10px] font-semibold bg-slate-100 text-slate-700">{categoryLabel(task.category)}</span></div><span className="font-black text-slate-900 text-base">€{task.estimatedCost}</span></div><div><h3 className="font-bold text-slate-900 text-sm leading-snug">{task.title}</h3><p className="text-xs text-slate-500 line-clamp-2 mt-1">{task.description}</p></div><div className="flex flex-wrap items-center gap-2 text-xs">{task.requiresTender&&<span className="px-2 py-0.5 rounded-md bg-teal-50 border border-teal-200 text-teal-800 text-[10px] font-bold flex items-center"><Building className="w-3 h-3 mr-1"/>{t.tenderOffers} ({task.tenderProposals.length})</span>}<span className="px-2 py-0.5 rounded-md text-[10px] font-bold bg-amber-50 border border-amber-200 text-amber-800">{auditLabel(task.financialAudit.status)}</span></div></div><div className="pt-3 border-t border-slate-100 flex items-center justify-between text-xs text-slate-500"><span>{l.createdBy} {task.creatorName}</span><span className="text-teal-700 font-bold inline-flex items-center">{l.inspect}</span></div></div>)}</div>
    {isCreatingTask&&<div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4"><div className="bg-white rounded-2xl max-w-lg w-full p-6 shadow-xl border border-slate-200 text-sm"><h3 className="font-bold text-slate-900 text-base pb-3 border-b border-slate-200">{t.createTask}</h3><form onSubmit={handleCreateSubmit} className="space-y-3 pt-3"><div><label className="block text-xs font-semibold text-slate-700 mb-1">{l.title}</label><input type="text" value={newTaskTitle} onChange={e=>setNewTaskTitle(e.target.value)} placeholder={l.titlePlaceholder} className="w-full px-3 py-2 border border-slate-300 rounded-lg text-xs font-semibold" required/></div><div className="grid grid-cols-2 gap-3"><div><label className="block text-xs font-semibold text-slate-700 mb-1">{l.category}</label><select value={newTaskCategory} onChange={e=>setNewTaskCategory(e.target.value as any)} className="w-full px-3 py-2 border border-slate-300 rounded-lg text-xs"><option value="maintenance">{l.categoryMaintenance}</option><option value="repairs">{l.categoryRepairs}</option><option value="landscaping">{l.categoryLandscaping}</option><option value="security">{l.categorySecurity}</option><option value="renovation">{l.categoryRenovation}</option></select></div><div><label className="block text-xs font-semibold text-slate-700 mb-1">{l.priority}</label><select value={newTaskPriority} onChange={e=>setNewTaskPriority(e.target.value as any)} className="w-full px-3 py-2 border border-slate-300 rounded-lg text-xs"><option value="low">{l.low}</option><option value="medium">{l.medium}</option><option value="high">{l.high}</option><option value="urgent">{l.urgent}</option></select></div></div><div><label className="block text-xs font-semibold text-slate-700 mb-1">{l.cost}</label><input type="number" min="10" value={newTaskCost} onChange={e=>setNewTaskCost(Number(e.target.value))} className="w-full px-3 py-2 border border-slate-300 rounded-lg text-xs font-bold" required/><p className="text-[11px] text-slate-500 mt-1">{newTaskCost>=500?l.tenderInfo:l.direct}</p></div><div><label className="block text-xs font-semibold text-slate-700 mb-1">{l.scope}</label><textarea rows={3} value={newTaskDesc} onChange={e=>setNewTaskDesc(e.target.value)} placeholder={l.descPlaceholder} className="w-full px-3 py-2 border border-slate-300 rounded-lg text-xs" required/></div><div className="flex justify-end space-x-2 pt-3 border-t border-slate-200"><button type="button" onClick={()=>setIsCreatingTask(false)} className="px-3 py-1.5 text-xs text-slate-600 border border-slate-300 rounded-lg font-semibold">{l.cancel}</button><button type="submit" className="px-4 py-1.5 text-xs bg-teal-600 text-white rounded-lg font-bold">{l.save}</button></div></form></div></div>}
    {activeTaskModal&&<TaskDetailModal task={activeTaskModal} onClose={()=>setActiveTaskModal(null)} onUpdateTask={updated=>{onUpdateTask(updated);setActiveTaskModal(updated)}} currentRole={currentRole} currentLang={currentLang}/>} 
  </div>;
};
