import React, { useState } from 'react';
import { X, MessageSquare, Send, Building, ShieldCheck, Check } from 'lucide-react';
import { TaskItem, UserRole, Language, FinancialAudit } from '../types';
import { translations } from '../i18n/translations';

interface TaskDetailModalProps { task: TaskItem; onClose: () => void; onUpdateTask: (task: TaskItem) => void; currentRole: UserRole; currentLang: Language; }

type ModalUi = { created:string; submitted:string; threshold:string; selected:string; reviewSummary:string; notesPlaceholder:string; flag:string; certify:string; registered:string; communication:string; commentPlaceholder:string; rejected:string; approved:string; days:string; };
const ui:Record<Language,ModalUi>={
 en:{created:'Created',submitted:'Submitted',threshold:'Threshold > €500 requires at least 3 competitive quotes',selected:'Selected',reviewSummary:'Financial Controller Review Summary / Audit Findings',notesPlaceholder:'Record audit verification notes or price market benchmark comparisons...',flag:'Flag Discrepancy',certify:'Certify Financial Audit',registered:'Registered',communication:'Communication & Work Notes',commentPlaceholder:'Add observation or technical note...',rejected:'Rejected / Revisions needed.',approved:'Approved in accordance with complex budget.',days:'Days'},
 ru:{created:'Создано',submitted:'предложений',threshold:'При стоимости > €500 требуется не менее 3 конкурентных предложений',selected:'Выбрано',reviewSummary:'Итоги проверки финансового контролёра / замечания аудита',notesPlaceholder:'Укажите результаты проверки или сравнение цены с рыночным уровнем...',flag:'Отметить расхождение',certify:'Подтвердить финансовую проверку',registered:'зарегистрировано',communication:'Комментарии и рабочие заметки',commentPlaceholder:'Добавьте замечание или техническую заметку...',rejected:'Отклонено / Требуется доработка.',approved:'Одобрено в соответствии с бюджетом комплекса.',days:'дн.'},
 tr:{created:'Oluşturuldu',submitted:'teklif',threshold:'€500 üzerindeki işler için en az 3 rekabetçi teklif gerekir',selected:'Seçildi',reviewSummary:'Mali Kontrolör İnceleme Özeti / Denetim Bulguları',notesPlaceholder:'Denetim notlarını veya piyasa fiyat karşılaştırmasını girin...',flag:'Farkı işaretle',certify:'Mali Denetimi Onayla',registered:'kayıtlı',communication:'İletişim ve Çalışma Notları',commentPlaceholder:'Gözlem veya teknik not ekleyin...',rejected:'Reddedildi / Revizyon gerekli.',approved:'Kompleks bütçesine uygun olarak onaylandı.',days:'gün'},
 fr:{created:'Créé',submitted:'soumissions',threshold:'Au-delà de 500 €, au moins 3 offres concurrentes sont requises',selected:'Sélectionné',reviewSummary:'Synthèse du contrôle financier / constats d’audit',notesPlaceholder:'Saisissez les notes de contrôle ou la comparaison du prix au marché...',flag:'Signaler un écart',certify:'Certifier le contrôle financier',registered:'enregistrés',communication:'Communication et notes de travail',commentPlaceholder:'Ajouter une observation ou une note technique...',rejected:'Rejeté / Révisions nécessaires.',approved:'Approuvé conformément au budget de la résidence.',days:'jours'},
 da:{created:'Oprettet',submitted:'tilbud',threshold:'Ved beløb over €500 kræves mindst 3 konkurrerende tilbud',selected:'Valgt',reviewSummary:'Finansiel kontrol / revisionsbemærkninger',notesPlaceholder:'Indtast kontrolnoter eller sammenligning med markedsprisen...',flag:'Markér afvigelse',certify:'Godkend finansiel kontrol',registered:'registreret',communication:'Kommunikation og arbejdsnoter',commentPlaceholder:'Tilføj observation eller teknisk note...',rejected:'Afvist / Kræver ændringer.',approved:'Godkendt i henhold til kompleksets budget.',days:'dage'},
 sv:{created:'Skapad',submitted:'offerter',threshold:'Över €500 krävs minst 3 konkurrerande offerter',selected:'Vald',reviewSummary:'Ekonomisk kontroll / revisionsresultat',notesPlaceholder:'Ange kontrollanteckningar eller jämförelse mot marknadspris...',flag:'Markera avvikelse',certify:'Godkänn ekonomisk kontroll',registered:'registrerade',communication:'Kommunikation och arbetsanteckningar',commentPlaceholder:'Lägg till observation eller teknisk anteckning...',rejected:'Avvisad / Ändringar krävs.',approved:'Godkänd enligt föreningens budget.',days:'dagar'},
 pl:{created:'Utworzono',submitted:'oferty',threshold:'Powyżej 500 € wymagane są co najmniej 3 konkurencyjne oferty',selected:'Wybrano',reviewSummary:'Podsumowanie kontroli finansowej / ustalenia audytu',notesPlaceholder:'Wpisz uwagi kontrolne lub porównanie ceny z rynkiem...',flag:'Zgłoś rozbieżność',certify:'Zatwierdź kontrolę finansową',registered:'zarejestrowane',communication:'Komunikacja i notatki robocze',commentPlaceholder:'Dodaj obserwację lub notatkę techniczną...',rejected:'Odrzucone / Wymagana korekta.',approved:'Zatwierdzone zgodnie z budżetem wspólnoty.',days:'dni'}
};

export const TaskDetailModal: React.FC<TaskDetailModalProps> = ({ task, onClose, onUpdateTask, currentRole, currentLang }) => {
  const t=translations[currentLang], l=ui[currentLang];
  const [commentText,setCommentText]=useState('');
  const [checklist,setChecklist]=useState(task.financialAudit.checklist||{tenderCompleted:false,proposalsVerified:false,priceReasonable:false,taxInvoiceAttached:false,boardApproved:false,proofOfExecutionAttached:false});
  const [auditNotes,setAuditNotes]=useState(task.financialAudit.notes||'');
  const canAudit=['admin','financial_controller'].includes(currentRole);
  const canVoteBoard=['admin','chairman','board_member'].includes(currentRole);
  const canSelectTender=['admin','management_company','chairman'].includes(currentRole);
  const priorityLabel={urgent:currentLang==='ru'?'Срочный':currentLang==='tr'?'Acil':currentLang==='fr'?'Urgente':currentLang==='da'?'Haster':currentLang==='sv'?'Brådskande':currentLang==='pl'?'Pilne':'Urgent',high:currentLang==='ru'?'Высокий':currentLang==='tr'?'Yüksek':currentLang==='fr'?'Élevée':currentLang==='da'?'Høj':currentLang==='sv'?'Hög':currentLang==='pl'?'Wysoki':'High',medium:currentLang==='ru'?'Средний':currentLang==='tr'?'Orta':currentLang==='fr'?'Moyenne':currentLang==='da'?'Mellem':currentLang==='sv'?'Medel':currentLang==='pl'?'Średni':'Medium',low:currentLang==='ru'?'Низкий':currentLang==='tr'?'Düşük':currentLang==='fr'?'Faible':currentLang==='da'?'Lav':currentLang==='sv'?'Låg':currentLang==='pl'?'Niski':'Low'}[task.priority];
  const handleToggleChecklist=(key:keyof typeof checklist)=>{if(!canAudit)return;setChecklist({...checklist,[key]:!checklist[key]});};
  const handleSaveAudit=(status:'verified_correct'|'discrepancy_flagged')=>{const updatedAudit:FinancialAudit={status,controllerName:'Ahmet Çelik (Financial Controller)',checkedAt:new Date().toISOString().split('T')[0],notes:auditNotes,checklist};onUpdateTask({...task,financialAudit:updatedAudit,status:status==='verified_correct'?'approved':'board_review'});};
  const handleBoardVote=(vote:'approve'|'reject')=>{const newVote={role:currentRole,memberName:currentRole==='chairman'?'Mehmet Demir (Chairman)':'Board Member',vote,comment:vote==='approve'?l.approved:l.rejected,votedAt:new Date().toISOString().split('T')[0]};onUpdateTask({...task,boardApprovals:[...(task.boardApprovals||[]).filter(v=>v.role!==currentRole),newVote],status:vote==='approve'?(task.requiresTender?'financial_audit':'approved'):'rejected'});};
  const handleSelectProposal=(propId:string)=>{if(!canSelectTender)return;onUpdateTask({...task,tenderProposals:task.tenderProposals.map(p=>({...p,isSelected:p.id===propId}))});};
  const handleAddComment=(e:React.FormEvent)=>{e.preventDefault();if(!commentText.trim())return;onUpdateTask({...task,comments:[...(task.comments||[]),{id:`comm-${Date.now()}`,authorName:currentRole.replace('_',' ').toUpperCase(),authorRole:currentRole,text:commentText.trim(),createdAt:new Date().toLocaleString()}]});setCommentText('');};

  return <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4"><div className="bg-white rounded-2xl max-w-3xl w-full max-h-[90vh] overflow-y-auto p-6 shadow-xl border border-slate-200 text-sm space-y-6">
    <div className="flex items-start justify-between pb-4 border-b border-slate-200"><div className="space-y-1"><div className="flex items-center space-x-2"><span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-slate-100 text-slate-700">{priorityLabel}</span><span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-teal-50 text-teal-800 border border-teal-200">{task.category}</span><span className="text-xs text-slate-600 font-mono">{l.created}: {task.createdAt}</span></div><h3 className="text-lg font-bold text-slate-900">{task.title}</h3><p className="text-xs text-slate-600 leading-relaxed">{task.description}</p></div><button onClick={onClose} className="p-1 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-100"><X className="w-5 h-5"/></button></div>
    {task.requiresTender&&<div className="bg-slate-50 p-4 rounded-2xl border border-slate-200 space-y-3"><div className="flex items-center justify-between"><h4 className="font-bold text-slate-900 text-xs uppercase tracking-wider flex items-center"><Building className="w-4 h-4 mr-1.5 text-teal-600"/>{t.tenderOffers} ({task.tenderProposals.length} {l.submitted})</h4><span className="text-[11px] text-slate-600">{l.threshold}</span></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-3">{task.tenderProposals.map(prop=><div key={prop.id} onClick={()=>handleSelectProposal(prop.id)} className={`p-3.5 rounded-xl border transition-all cursor-pointer flex flex-col justify-between ${prop.isSelected?'bg-teal-50/90 border-teal-500 ring-2 ring-teal-500/20 shadow-xs':'bg-white border-slate-200 hover:border-slate-300'}`}><div className="space-y-1"><div className="flex items-center justify-between"><span className="font-bold text-xs text-slate-900 truncate">{prop.contractorName}</span>{prop.isSelected&&<span className="p-0.5 bg-teal-600 text-white rounded-full"><Check className="w-3 h-3"/></span>}</div><p className="text-[11px] text-slate-500 leading-tight line-clamp-2">{prop.scopeSummary}</p></div><div className="mt-3 pt-2 border-t border-slate-100 flex items-center justify-between"><span className="font-black text-slate-900 text-sm">€{prop.price}</span><span className="text-[10px] text-slate-600">{prop.validityPeriod}</span></div></div>)}</div></div>}
    <div className="bg-amber-50/50 p-4 rounded-2xl border border-amber-200/80 space-y-4"><div className="flex items-center justify-between"><div className="flex items-center space-x-2"><ShieldCheck className="w-5 h-5 text-amber-700"/><h4 className="font-bold text-slate-900 text-xs uppercase tracking-wider">{t.financialControllerChecklist}</h4></div><span className={`px-2.5 py-0.5 rounded-full text-xs font-bold ${task.financialAudit.status==='verified_correct'?'bg-emerald-100 text-emerald-800 border border-emerald-300':task.financialAudit.status==='discrepancy_flagged'?'bg-rose-100 text-rose-800 border border-rose-300':'bg-amber-100 text-amber-800'}`}>{task.financialAudit.status==='verified_correct'?t.auditCorrect:task.financialAudit.status==='discrepancy_flagged'?t.auditDiscrepancy:t.auditPending}</span></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">{[{key:'tenderCompleted',label:t.tenderCompleted},{key:'proposalsVerified',label:t.proposalsVerified},{key:'priceReasonable',label:t.priceReasonable},{key:'taxInvoiceAttached',label:t.taxInvoiceAttached},{key:'boardApproved',label:t.boardApproved},{key:'proofOfExecutionAttached',label:t.proofAttached}].map(({key,label})=>{const checked=(checklist as any)[key]||false;return <button key={key} type="button" onClick={()=>handleToggleChecklist(key as any)} disabled={!canAudit} className={`flex items-center p-2 rounded-lg border text-left ${checked?'bg-emerald-50 border-emerald-300 text-emerald-950 font-semibold':'bg-white border-slate-200 text-slate-600'}`}><span className={`w-4 h-4 rounded mr-2 flex items-center justify-center border ${checked?'bg-emerald-600 border-emerald-600 text-white':'border-slate-300 bg-white'}`}>{checked&&<Check className="w-3 h-3"/>}</span><span className="text-[11px]">{label}</span></button>})}</div><div className="space-y-2 pt-2"><label className="block text-[11px] font-bold text-slate-700 uppercase">{l.reviewSummary}</label><textarea rows={2} value={auditNotes} onChange={e=>setAuditNotes(e.target.value)} disabled={!canAudit} placeholder={l.notesPlaceholder} className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs"/>{canAudit&&<div className="flex items-center justify-end space-x-2 pt-2"><button type="button" onClick={()=>handleSaveAudit('discrepancy_flagged')} className="px-3 py-1.5 bg-rose-50 text-rose-800 border border-rose-300 rounded-lg text-xs font-bold">{l.flag}</button><button type="button" onClick={()=>handleSaveAudit('verified_correct')} className="px-4 py-1.5 bg-emerald-600 text-white rounded-lg text-xs font-bold">{l.certify}</button></div>}</div></div>
    <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200 space-y-3"><div className="flex items-center justify-between"><h4 className="font-bold text-slate-900 text-xs uppercase tracking-wider">{t.boardApproval} ({task.boardApprovals?.length||0} {l.registered})</h4>{canVoteBoard&&<div className="flex space-x-2"><button onClick={()=>handleBoardVote('reject')} className="px-2.5 py-1 bg-white border border-rose-300 text-rose-700 rounded-lg text-xs font-bold">{t.voteReject}</button><button onClick={()=>handleBoardVote('approve')} className="px-3 py-1 bg-emerald-600 text-white rounded-lg text-xs font-bold">{t.voteApprove}</button></div>}</div>{task.boardApprovals?.map((vote,idx)=><div key={idx} className="p-2.5 bg-white rounded-xl border border-slate-200 flex items-center justify-between text-xs"><div><span className="font-bold text-slate-900">{vote.memberName}</span><p className="text-slate-500 text-[11px]">{vote.comment}</p></div><span className={`px-2 py-0.5 rounded-md font-bold text-[10px] ${vote.vote==='approve'?'bg-emerald-100 text-emerald-800':'bg-rose-100 text-rose-800'}`}>{vote.vote.toUpperCase()}</span></div>)}</div>
    <div className="space-y-3"><h4 className="font-bold text-slate-900 text-xs uppercase tracking-wider flex items-center"><MessageSquare className="w-4 h-4 mr-1.5 text-teal-600"/>{l.communication}</h4><div className="space-y-2 max-h-36 overflow-y-auto">{(task.comments||[]).map(comm=><div key={comm.id} className="p-2.5 bg-slate-50 rounded-xl border border-slate-100 text-xs"><div className="flex justify-between font-bold text-slate-800 text-[11px]"><span>{comm.authorName} ({comm.authorRole})</span><span className="text-slate-600 font-normal">{comm.createdAt}</span></div><p className="text-slate-600 mt-1">{comm.text}</p></div>)}</div><form onSubmit={handleAddComment} className="flex gap-2"><input type="text" value={commentText} onChange={e=>setCommentText(e.target.value)} placeholder={l.commentPlaceholder} className="flex-1 px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs"/><button type="submit" className="px-3 py-2 bg-teal-600 text-white rounded-xl text-xs font-bold"><Send className="w-3.5 h-3.5"/></button></form></div>
  </div></div>;
};
